### ISSUE TITLE
Initial run issue

### ISSUE THREAD

**Issue by americavotesdata** [villasv/turbine#127]
Hi,
I'm pretty sure that the problem is due to my ignorance with the platform; but when I ssh into the scheduler and webserver instances, they don't have airflow installed. It's like CF neglected to run the commands in the template. Is there a step I'm missing?
Thanks

**Comment by villasv** [comment]
Whoops, looks like I missed the email for this issue. I'm so sorry @americavotesdata :-( I'm ashamed to answer almost a year later, hopefully you were able to get going even if not using this stack.

Thanks for reporting this behavior. Since there was a major release since that, I'm going to close this issue as wontfix because if the problem still persists, it probably manifests itself differently today. Maybe related to https://github.com/villasv/aws-airflow-stack/issues/149.

Sorry again, happy DAGs.
